language: php

php:
  - 5.3
  - 5.4
  
env:
  - SYMFONY_VERSION=2.4.*

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}
  
script: phpunit --coverage-clover "clover"

after_success:
    - curl -sL https://bit.ly/artifact-uploader | php

notifications:
  email:
    - email@fabiansteiner.com